export default {
  signin: require('./signin.png'),
  bulb: require('./bulbblue.png'),
  cylinder: require('./gas.png'),
  mobile: require('./premobile.png'),
  dth: require('./dthnetwork.png'),
  landline: require('./telephone.png'),
  water: require('./water.png'),
  loanPayment: require('./loan.png'),
  broadband: require('./broadband.png'),
  pan: require('./pan.png'),
  microAtm: require('./microatm.png'),
  enquiry: require('./enquiry.png'),
  withdrawal: require('./withdrawal.png'),
  miniStatement: require('./miniStatement.png'),
  wallet: require('./wallet.png'),
  bank: require('./bank.png'),
  userImage: require('./avatar.png'),
  bankIcon: require('./bank-icon.png'),
  greenTick: require('./yes.png'),
  aeps: require('./aeps-icon.png'),
  fastag: require('./fastag.png'),
  banks: require('./money-transfer.png'),
  postmobile: require('./postmobile.png'),
};
