export enum Routes {
  Signin = 'Signin',
  HomeStack = 'HomeStack',
  DrawerNav = 'DrawerNav',
  DrawerScreen = 'DrawerScreen',
  HomeScreen = 'HomeScreen',
  IncomeReport = 'Income Report',
  MoneyTransferReport = 'Money Transfer Report',
  RechargeReports = 'Recharge Reports',
  AccountStatement = 'Account Statement',
  OperatorReport = 'Operator Report',
  PaymentRequestReports = 'Payment Request Reports',
  PaymentRequest = 'Payment Request',
  BalanceReturnRequest = 'Balance Return Request',
  Dispute = 'Dispute',
  MyCommission = 'My Commission',
  About = 'About',
  ContactUs = 'Contact Us',
  ElectricityProvider = 'ElectricityProvider',
  PostpaidProvider = 'PostPaid Provider',
  DthProvider = 'DTH Provider',
  MobileProvider = 'MobileProvider',
  ProviderStack = 'ProviderStack',
  ProviderDetails = 'ProviderDetails',
  MoneyTransfer1 = 'Customer Number',
  PanCard = 'Pan Card',
  MicroAtm = 'Micro ATM',
}
