export const ScreenStrings = {
  appName: 'ExplorePortals',
  morning: 'Good Morning',
  afternoon: 'Good Afternoon',
  evening: 'Good Evening',
  share: 'Share',
  logout: 'Logout',
  newUser: 'New User?',
  register: 'Register',
  login: 'Login',
  tryAgain: 'Something went wrong. Try Again',
  selectYourChoice: 'Select Your Choice',
  balance: 'Balance',
  aesBalance: 'AES Balance',
  utitslUserId: 'UTITSL User ID',
  quantity: 'Quantity',
  selectQuantity: 'Select Quantity',
  id: 'ID',
  dateTime: 'Date Time',
  txnid: 'Txnid',
  description: 'Description',
  op: 'OP',
  debit: 'Debit',
  credit: 'Credit',
  profit: 'Profit',
  cl: 'CL',
  name: 'Name',
  opBal: 'OP Bal',
  clBal: 'CL Bal',
  crAmount: 'CR Amount',
  drAmount: 'DR Amount',
  sales: 'Sales',
  charges: 'Charges',
  pending: 'Pending',
  action: 'Action',
  minAmount: 'Min Amount',
  maxAmount: 'Max Amount',
  commission: 'Commission/Charges',
  providerId: 'Provider ID',
  providerName: 'Provider Name',
  service: 'Service',
  requestedBy: 'Requested By :',
  date: 'Date :',
  remark: 'Remark :',
  amount: 'Amount :',
  approve: 'Approve',
  exit: 'Exit',
  proceed: 'Proceed',
  status: 'Status',
  loginPassword: 'Login Password',
  customerMobileNumber: 'Customer Mobile Number',
  customeraadhaarNumber: 'Customer Aadhaar Number',
  device: 'Device',
  scanNow: 'SCAN NOW',
  selectDevice:"Select Device"
};

export const ValidationStrings = {
  required: 'It is a required field.',
  min: 'Minimum 8 character required.',
  invalidMail: 'Invalid Email.',
  min3: 'Minimum 3 characters required',
};

export const Placeholder = {
  searchHeaderPlaceholder: 'Enter your biller name',
  aadhaarNumber : "Aadhaar Number",
  phoneNumber : "Phone Number"
};
