export const ScreenStrings = {
  appName: 'ExplorePortals',
  morning: 'Good Morning',
  afternoon: 'Good Afternoon',
  evening: 'Good Evening',
  share: 'Share',
  logout: 'Logout',
  newUser: 'New User?',
  register: 'Register',
  login: 'Login',
  tryAgain: 'Something went wrong. Try Again',
  selectYourChoice: 'Select Your Choice',
  balance: 'Balance',
  aesBalance: 'AES Balance',
  utitslUserId: 'UTITSL User ID',
  quantity: 'Quantity',
  selectQuantity: 'Select Quantity',
  id: 'ID',
  dateTime: 'Date Time',
  txnid: 'Txnid',
  description: 'Description',
  op: 'OP',
  debit: 'Debit',
  credit: 'Credit',
  profit: 'Profit',
  cl: 'CL',
  name: 'Name',
  opBal: 'OP Bal',
  clBal: 'CL Bal',
  crAmount: 'CR Amount',
  drAmount: 'DR Amount',
  sales: 'Sales',
  charges: 'Charges',
  pending: 'Pending',
  action: 'Action',
  minAmount: 'Min Amount',
  maxAmount: 'Max Amount',
  commission: 'Commission/Charges',
  providerId: 'Provider ID',
  providerName: 'Provider Name',
  service: 'Service',
  requestedBy: 'Requested By :',
  date: 'Date :',
  remark: 'Remark :',
  amount: 'Amount :',
  approve: 'Approve',
  exit: 'Exit',
  proceed: 'Proceed',
  status: 'Status',
  loginPassword: 'Login Password',
  customerMobileNumber: 'Customer Mobile Number',
  customeraadhaarNumber: 'Customer Aadhaar Number',
  device: 'Device',
  scanNow: 'SCAN NOW',
  selectDevice: 'Select Device',
  profile: 'Profile',
  addMoney: 'Add Money',
  upiCollection: 'UPI Collection',
  changePassword: 'Change Password',
  update: 'Update Password',
  permanentAddress: 'Permanent Address',
  presentAddress: 'Present Address',
  upiQrCode: 'UPI QR Code',
  success: 'Success',
  customerNumber: 'Customer No.',
  commissionText: 'Commission',
  transcationId: 'Transaction ID',
  dateAndTime: 'Date & Time',
  dispute: 'Dispute',
  reportId: 'Report ID',
  provider: 'Provider',
  number: 'Number',
  message: 'Message',
  close: 'Close',
  submit: 'Submit',
  chooseReason: 'Choose Reason',
  view: 'View',
  get: 'Get',
  from: 'From',
  to: 'To',
  utr: 'UTR/Bank Reference',
  amounts: 'Amount',
  selectDepositedBank: 'Select Deposited Bank',
  selectPaymentMethod: 'Select Payment Method',
  paymentDepositdate: 'Payment Deposit Date',
  dateFormat: 'YYYY-MM-DD',
  proceedToPay: 'Proceed To Pay',
};

export const ValidationStrings = {
  required: 'It is a required field.',
  min: 'Minimum 8 character required.',
  invalidMail: 'Invalid Email.',
  min3: 'Minimum 3 characters required',
  noMatch: 'Password does not match.',
  aadhaarInvalid: 'Aadhar number is not valid',
  phoneInvalid: 'Phone Number is not valid',
  negativeAmount: "Amount can't be negative.",
  invalidAmount: 'Please enter a valid amount.',
};

export const Placeholder = {
  searchHeaderPlaceholder: 'Enter your biller name',
  aadhaarNumber: 'Aadhaar Number',
  phoneNumber: 'Phone Number',
  confirmPassword: 'Confirm Password',
  newPassword: 'New Password',
  currentPassword: 'Current Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  address: 'Address',
  city: 'City',
  pinCode: 'Pin Code',
  district: 'District',
  shopName: 'Shop Name',
  upiId: 'Enter UPI ID',
  amount: 'Amount',
  remark: 'Remark',
  enterMessage: 'Enter Message Here....',
};
